INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Plauen', 'Blumenweg', 94, 61, 42);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Bad Segeberg', 'Blumenweg', 25, 69, 5);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Villingen-Schwenningen', 'Blumenweg', 18, 59, 23);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Weiden', 'Dorfstrasse', 98, 60, 40);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Landsberg', 'Schulstrasse', 84, 86, 7);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Neuwied', 'Bahnhofstrasse', 56, 10, 78);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Salzwedel', 'Dorfstrasse', 39, 77, 56);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Passau', 'Hauptstrasse', 86, 1, 17);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Essen', 'Hauptstrasse', 6, 43, 21);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Birkenfeld', 'Blumenweg', 75, 69, 15);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Cloppenburg', 'Blumenweg', 75, 85, 49);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Osterholz-Scharmbeck', 'Schulstrasse', 48, 27, 25);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Emden', 'Heuweg', 30, 30, 54);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Eisenach', 'Dorfstrasse', 23, 10, 20);
INSERT INTO clients_address (city, street, house, floor, flat_number) VALUES ('Coburg', 'Schulstrasse', 69, 45, 66);
